#!/bin/bash

if [ "$HOSTNAME" != "chl-server" ]; then
  echo "Called from local client. Re-running against remote server"
  ssh chl < ./deploy
else
  REPO_DIR=/root/Documents/code/strongcode-client
  DEPLOY_DIR=/var/www/strongcode-client

  cd $REPO_DIR
  echo "cd into $REPO_DIR and pulling new changes..."
  git pull

  echo "Removing old $DEPLOY_DIR"
  rm -rf $DEPLOY_DIR

  mkdir -p $DEPLOY_DIR 

  echo "Copying distributable to $DEPLOY_DIR"
  cp -r $REPO_DIR/dist/* $DEPLOY_DIR

  service nginx restart
fi
